### ISSUE TITLE
rename project 

### ISSUE THREAD

**Issue by maxxedev** [thunkware/virtual-threads-bridge#13]
Some people argue that this project is not really a backport, strictly speaking. Rename to loom-bridge

**Comment by juliojgd** [comment]
I'm not sure if to include loom in the name is a good idea as Project Loom (AFAIK) includes more than Virtual Threads, so people could expect to find here more than the VT adapters.

**Comment by maxxedev** [comment]
Ok, will rename to virtual-threads-bridge
