### ISSUE TITLE
Fix typo in "SempahoreExecutor" 

### ISSUE THREAD

**Issue by juliojgd** [thunkware/virtual-threads-bridge#24]
https://github.com/thunkware/virtual-threads-bridge/blob/096fa0f06164fb2bacb3933636c09b70cc3d96bf/src/main/java/io/github/thunkware/vt/bridge/SempahoreExecutor.java#L18

My proposal is to deprecate the class "SempahoreExecutor.java" (due to the typo in its name) in favor of "SemaphoreExecutor.java"

I would perform these steps:

1. Create "SemaphoreExecutor.java" 
2. Move all the working code to the newly created class
3. Delegate all calls in "SempahoreExecutor.java" methods to the corresponding methods in "SemaphoreExecutor.java"
4. Mark "SempahoreExecutor.java" as deprecated for removal

The intention is not making a breaking change.

If you think it makes sense I can try to contribute a PR.

Thanks in advance

**Comment by maxxedev** [comment]
I would
1. Create SemaphoreExecutor.java
2. Modify SempahoreExecutor.java to subclass SemaphoreExecutor.java
3. Mark "SempahoreExecutor.java" as deprecated for removal

**Comment by maxxedev** [comment]
Yes, if you can contribute a PR, that'd be great.
